name: Consortium Membership
description: Application to become a Safety Critical Rust Consortium Member
title: Membership Application for [INSERT COMPANY, INSTITUTION, YOUR NAME, OR OTHER ENTITY]
labels: ["membership application"]
assignees: 
  - joelmarcey
body:
  - type: markdown
    attributes:
      value: |
        The [Safety Critical Rust Consortium](https://github.com/rustfoundation/safety-critical-rust-consortium) was [announced](https://foundation.rust-lang.org/news/announcing-the-safety-critical-rust-consortium/) in June 2024 with a goal to support the responsible use of Rust in Safety Critical software. The mission of the consortium is to improve the suitability of Rust in safety critical applications.
        
        Membership into the consortium is free and available to those with a noted and vested interested in the safety critical space. There are two types of membership:
        - Producer: An active participant in the consortium, helping drive its mission
        - Observers: A passive participant who wants to keep up with the consortium's happenings. Observers generally virtually attend meetings and listen in.
        
        This distinction is mainly for housekeeping purposes. You can choose which type of membership you plan to be initially and change it as needed.

        If you do become a member of the consortium, you will be added to the consortium mailing list, which is currently the only non-public asset of the consortium at this point.

        Also, don't forget to join the consortium's [Zulip channel](https://rust-lang.zulipchat.com/#narrow/channel/445688-safety-critical-consortium).

        > Note that the name, email address, and any company you provide will be public since GitHub issues are public. We do not use your information for any reason other than for membership purposes.
  - type: input
    id: Name
    attributes:
      label: What is your name?
    validations:
      required: true
  - type: input
    id: Email
    attributes:
      label: What is your preferred email address?
    validations:
      required: true
  - type: dropdown
    id: representation
    attributes:
      label: Do you represent a company, institution, consortium, yourself or other entity?
      description: In what capacity will you be represented as a member of the consortium?
      options:
        - Company
        - Institution (Academic, etc.)
        - Consortium
        - Myself
        - Other Entity
      default: 0
    validations:
      required: true
  - type: textarea
    id: entity-name
    attributes:
      label: If you represent a company, institution, consortium, or other entity, please enter it here.
      description: If you are representing other than yourself, please enter it. Otherwise, type 'Individual'.
      placeholder: Type company or entity name, or type "Individual" 
    validations:
      required: true
  - type: textarea
    id: why-interested
    attributes:
      label: Why are you interested in joining the Safety Critical Rust Consortium?
      description: If applicable, describe work that you are doing or planning to do in the safety critical space.
    validations:
      required: true
  - type: dropdown
    id: membership-type
    attributes:
      label: Do you plan to be a producer or observer in the consortium?
      description: See above for the distinction between these two membership types. They are used mainly for housekeeping purposes and can be changed.
      options:
        - Producer
        - Observer
      default: 1
    validations:
      required: true
