name: Submit Safety Critical Tool
description: Submit a safety-critical tool to the consortium
title: Safety-Critical Tool Submission
labels: ["submit tooling"]
assignees:
  - joelmarcey, alexandruradovici
body:
  - type: markdown
    attributes:
      value: |
        ## Submit a Tool to the Consortium
        If you maintain, sell, or use a software tool that would be useful to the safety-critical Rust community we want to hear about it. This might include statis analysis, hardware deployment, compilers, or libraries/crates.

        The consortium may publicize this tool on email publications, websites ([Are We Safety Critical Yet](www.arewesafetycriticalyet.com)), or at meetings. If we decide to move ahead with featuring the tool we will request more information about the specific uses of the tool as well as ask for a point-of-contact.

        However, we may also deem the tool as not safety-critical, not mature enough (yet), or unmaintained and decline to publish it. In that case we would be happy to reconsider the tool in the future as it develops.
  - type: input
    id: tool_name
    attributes:
      label: What is the name of the tool?
    validations:
      required: true
  - type: textarea
    id: tool_description
    attributes:
      label: Add a concise description of the tool. Please refrain from marketing claims and stick to what it does and how it would be used?
    validations:
      required: true
  - type: input
    id: tool_link
    attributes:
      label: Link to the tool repo or homepage
    validations:
      required: true
  - type: input
    id: tool_license
    attributes:
      label: License of the tool
    validations:
      required: true
  - type: dropdown
    id: submitter_role
    attributes:
      label: What is your role/connection to this tool?
      description: What do you do for/with this tool
      options:
        - 'User or Customer'
        - 'Creator/Maintainer (open source)'
        - 'Product Manager/Owner (commercial)'
        - 'Other'
    validations:
      required: true
  - type: input
    id: tool_vendor
    attributes:
      label: Optional name of the tool vendor
    validations:
      required: false
  - type: input
    id: tool_liability
    attributes:
      label: Optional liability provided by the tool vendor
    validations:
      required: false
  - type: input
    id: tool_qualification
    attributes:
      label: List any standards the tool is qualified for
    validations:
      required: false
  - type: dropdown
    id: tool_type
    attributes:
      label: Tool category
      description: Specific use and type of this tool
      options:
        - "code-coverage"
        - "requirements-traceability"
        - "compiler"
        - "test-runner"
        - "formal-verification"
        - "static-analysis"
        - "tests-generation"
        - "package-manager"
        - "profiler"
        - "debugger"
    validations:
      required: false
